DROP TABLE "bit_systems"."bin";--> statement-breakpoint
DROP TABLE "bit_systems"."bin_item";--> statement-breakpoint
DROP TABLE "bit_systems"."stock_item";--> statement-breakpoint
DROP TABLE "bit_systems"."traceable_bin_item";--> statement-breakpoint
DROP TABLE "bit_systems"."traceable_item";--> statement-breakpoint
DROP TABLE "bit_systems"."warehouse";--> statement-breakpoint
DROP TABLE "component";--> statement-breakpoint
DROP TABLE "component_category";--> statement-breakpoint
DROP TABLE "department";--> statement-breakpoint
DROP TABLE "subcomponent";--> statement-breakpoint
DROP TABLE "customer";--> statement-breakpoint
DROP TABLE "sales_despatch";--> statement-breakpoint
DROP TABLE "sales_despatch_item";--> statement-breakpoint
DROP TABLE "sales_order";--> statement-breakpoint
DROP TABLE "sales_order_item";--> statement-breakpoint
DROP TABLE "batch";--> statement-breakpoint
DROP TABLE "batch_movement";--> statement-breakpoint
DROP TABLE "batch_movement_correction";--> statement-breakpoint
DROP TABLE "location";--> statement-breakpoint
DROP TABLE "location_group";--> statement-breakpoint
DROP TABLE "location_type";--> statement-breakpoint
DROP TABLE "task";--> statement-breakpoint
DROP TABLE "task_item";--> statement-breakpoint
DROP TABLE "production_batch_input";--> statement-breakpoint
DROP TABLE "production_batch_output";--> statement-breakpoint
DROP TABLE "production_job";--> statement-breakpoint
DROP TABLE "profile";--> statement-breakpoint
DROP TABLE "purchase_order";--> statement-breakpoint
DROP TABLE "purchase_order_item";--> statement-breakpoint
DROP TABLE "purchase_receipt";--> statement-breakpoint
DROP TABLE "purchase_receipt_item";--> statement-breakpoint
DROP TABLE "supplier";--> statement-breakpoint
DROP TABLE "sage"."ACCOUNT_STATUS";--> statement-breakpoint
DROP TABLE "sage"."ACCRUAL";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_HEADER";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_HISTORY_HEADER";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_HISTORY_JOURNAL";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_HISTORY_SPLIT";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_HISTORY_USAGE";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_JOURNAL";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_SPLIT";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_USAGE";--> statement-breakpoint
DROP TABLE "sage"."AUDIT_VAT";--> statement-breakpoint
DROP TABLE "sage"."BANK";--> statement-breakpoint
DROP TABLE "sage"."BANK_STATEMENT";--> statement-breakpoint
DROP TABLE "sage"."BANK_STATEMENT_LINE";--> statement-breakpoint
DROP TABLE "sage"."CALENDAR_EVENT";--> statement-breakpoint
DROP TABLE "sage"."CALENDAR_EVENT_LABEL";--> statement-breakpoint
DROP TABLE "sage"."CALENDAR_EVENT_LOCATION";--> statement-breakpoint
DROP TABLE "sage"."CALENDAR_EVENT_RECURRENCE_PATTERN";--> statement-breakpoint
DROP TABLE "sage"."CATEGORY";--> statement-breakpoint
DROP TABLE "sage"."CAT_TITLE";--> statement-breakpoint
DROP TABLE "sage"."CHART_LIST";--> statement-breakpoint
DROP TABLE "sage"."CIS_RETURN";--> statement-breakpoint
DROP TABLE "sage"."CIS_RETURN_TRANSACTION";--> statement-breakpoint
DROP TABLE "sage"."CIS_SETTINGS";--> statement-breakpoint
DROP TABLE "sage"."CIS_SUBCONTRACTOR";--> statement-breakpoint
DROP TABLE "sage"."CIS_SUBCONTRACTOR_LEGACY";--> statement-breakpoint
DROP TABLE "sage"."CIS_SUBCONTRACTOR_RETURN";--> statement-breakpoint
DROP TABLE "sage"."CIS_SUBCONTRACTOR_TAX_HISTORY";--> statement-breakpoint
DROP TABLE "sage"."CLEARED_TRAN_RANGE";--> statement-breakpoint
DROP TABLE "sage"."CLEAR_AUDIT_TRAIL_EVENT";--> statement-breakpoint
DROP TABLE "sage"."COMMUNICATION_ADDRESS";--> statement-breakpoint
DROP TABLE "sage"."COMPANY";--> statement-breakpoint
DROP TABLE "sage"."COMPANY_DEL_ADDR";--> statement-breakpoint
DROP TABLE "sage"."CONTACT_HISTORY";--> statement-breakpoint
DROP TABLE "sage"."CONTACT_HISTORY_CONTACT_OUTCOME";--> statement-breakpoint
DROP TABLE "sage"."CONTACT_HISTORY_CONTACT_TYPE";--> statement-breakpoint
DROP TABLE "sage"."CONTACT_HISTORY_MAJOR_TYPE";--> statement-breakpoint
DROP TABLE "sage"."COUNTRY_CODE";--> statement-breakpoint
DROP TABLE "sage"."CREDIT_BUREAU";--> statement-breakpoint
DROP TABLE "sage"."CURRENCY";--> statement-breakpoint
DROP TABLE "sage"."DELETED_RECORDS";--> statement-breakpoint
DROP TABLE "sage"."DEPARTMENT";--> statement-breakpoint
DROP TABLE "sage"."DIRECT_DEBIT_PAYMENT_REQUESTS";--> statement-breakpoint
DROP TABLE "sage"."DISPUTE_REASON";--> statement-breakpoint
DROP TABLE "sage"."ECSALES_FILL";--> statement-breakpoint
DROP TABLE "sage"."ECSALES_HEADER";--> statement-breakpoint
DROP TABLE "sage"."ECSALES_SPLIT";--> statement-breakpoint
DROP TABLE "sage"."EC_VAT_DESCRIPTION";--> statement-breakpoint
DROP TABLE "sage"."ESUBMISSION_SETTINGS";--> statement-breakpoint
DROP TABLE "sage"."FINANCIAL_BUDGET";--> statement-breakpoint
DROP TABLE "sage"."FIXED_ASSET";--> statement-breakpoint
DROP TABLE "sage"."FIXED_ASSET_CAT";--> statement-breakpoint
DROP TABLE "sage"."FUND";--> statement-breakpoint
DROP TABLE "sage"."FUND_TYPE";--> statement-breakpoint
DROP TABLE "sage"."GDN_ITEM";--> statement-breakpoint
DROP TABLE "sage"."GRN_ITEM";--> statement-breakpoint
DROP TABLE "sage"."INTRASTAT";--> statement-breakpoint
DROP TABLE "sage"."INVOICE";--> statement-breakpoint
DROP TABLE "sage"."INVOICE_ITEM";--> statement-breakpoint
DROP TABLE "sage"."LETTER_TYPE";--> statement-breakpoint
DROP TABLE "sage"."NOMINAL_LEDGER";--> statement-breakpoint
DROP TABLE "sage"."PAYMENT_INFO";--> statement-breakpoint
DROP TABLE "sage"."PAYMENT_METHOD";--> statement-breakpoint
DROP TABLE "sage"."PERIOD";--> statement-breakpoint
DROP TABLE "sage"."POP_ITEM";--> statement-breakpoint
DROP TABLE "sage"."PREPAYMENT";--> statement-breakpoint
DROP TABLE "sage"."PRICE";--> statement-breakpoint
DROP TABLE "sage"."PRICE_LIST";--> statement-breakpoint
DROP TABLE "sage"."PROJECT";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_BUDGET";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_COST_CODE";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_COST_TYPE";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_ONLY_TRAN";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_RELATIONSHIP";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_RESOURCE";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_RESOURCE_TYPE";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_REVENUE_CODE";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_STATUS";--> statement-breakpoint
DROP TABLE "sage"."PROJECT_TRAN";--> statement-breakpoint
DROP TABLE "sage"."PROTX_PAYMENT";--> statement-breakpoint
DROP TABLE "sage"."PURCHASE_DEL_ADDR";--> statement-breakpoint
DROP TABLE "sage"."PURCHASE_LEDGER";--> statement-breakpoint
DROP TABLE "sage"."PURCHASE_ORDER";--> statement-breakpoint
DROP TABLE "sage"."RECURRING";--> statement-breakpoint
DROP TABLE "sage"."REMITTANCE";--> statement-breakpoint
DROP TABLE "sage"."RTD_SUMMARY";--> statement-breakpoint
DROP TABLE "sage"."SAGEPAY_PAY_BY_LINK";--> statement-breakpoint
DROP TABLE "sage"."SALES_DEL_ADDR";--> statement-breakpoint
DROP TABLE "sage"."SALES_LEDGER";--> statement-breakpoint
DROP TABLE "sage"."SALES_ORDER";--> statement-breakpoint
DROP TABLE "sage"."SOFA_CATEGORY";--> statement-breakpoint
DROP TABLE "sage"."SOP_ITEM";--> statement-breakpoint
DROP TABLE "sage"."STOCK";--> statement-breakpoint
DROP TABLE "sage"."STOCK_ALLOCATION";--> statement-breakpoint
DROP TABLE "sage"."STOCK_CAT";--> statement-breakpoint
DROP TABLE "sage"."STOCK_COMP";--> statement-breakpoint
DROP TABLE "sage"."STOCK_TRAN";--> statement-breakpoint
DROP TABLE "sage"."SUPPLIER_PAYMENT_INFO";--> statement-breakpoint
DROP TABLE "sage"."TAX_CODE";--> statement-breakpoint
DROP TABLE "sage"."UPDATE_LEDGER";--> statement-breakpoint
DROP TABLE "sage"."VAT_ADJUSTMENT";--> statement-breakpoint
DROP TABLE "sage"."VAT_DETAILS";--> statement-breakpoint
DROP TABLE "sage"."VAT_RETURN";--> statement-breakpoint
DROP TABLE "sage"."VAT_RETURN_RECEIPT";--> statement-breakpoint
DROP TABLE "sage"."VAT_REV_CHARGE_DETAIL";--> statement-breakpoint
DROP TABLE "sage"."VAT_REV_CHARGE_HEADER";--> statement-breakpoint
DROP TABLE "sage"."VAT_REV_CHARGE_RETURN";--> statement-breakpoint
DROP TABLE "sage"."VAT_SUMMARY";--> statement-breakpoint
DROP SCHEMA "bit_systems";
--> statement-breakpoint
DROP SCHEMA "sage";
